<?php

use Illuminate\Database\Seeder;

class TechsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('techs')->insert([
            [
                'member_id' => 1,
                'team_id' => 1,
                'language_id' => 1,
                'code' => "<html>\n\t<h1>HTML文章です</h1>\n\t<a href=\"http://apple.com\">タグです</a>\n</html>",
                'command' => null,
                'link' => null,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'member_id' => 1,
                'team_id' => 1,
                'language_id' => 2,
                'code' => "h1 {\n\tcolor: #fff;\n\tfont-size: 14px;\n}",
                'command' => null,
                'link' => null,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'member_id' => 1,
                'team_id' => 2,
                'language_id' => 4,
                'code' => "<?php\nfunction calCircleArea(\$radius) {\n\t\$pai = 3.14;\n\t\$area = \$radius * \$radius * \$pai;\n\treturn \$area;\n}\n?>",
                'command' => null,
                'link' => null,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'member_id' => 1,
                'team_id' => 2,
                'language_id' => 3,
                'code' => "const btn = $('#btn');\nbtn.on('click', function() {\n\talert('error');\n});",
                'command' => null,
                'link' => null,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'member_id' => 1,
                'team_id' => 1,
                'language_id' => 2,
                'code' => null,
                'command' => null,
                'link' => "https://www.sassmeister.com/",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'member_id' => 1,
                'team_id' => 2,
                'language_id' => 3,
                'code' => null,
                'command' => null,
                'link' => "https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'member_id' => 1,
                'team_id' => 4,
                'language_id' => 4,
                'code' => null,
                'command' => null,
                'link' => "https://www.php.net/",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'member_id' => 1,
                'team_id' => 5,
                'language_id' => 11,
                'code' => null,
                'command' => "$ mysql.server status",
                'link' => "https://www.mysql.com/",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'member_id' => 1,
                'team_id' => 1,
                'language_id' => 5,
                'code' => null,
                'command' => null,
                'link' => "http://www.ne.jp/asahi/hishidama/home/tech/java/index.html",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'member_id' => 1,
                'team_id' => 1,
                'language_id' => 4,
                'code' => null,
                'command' => "composer dumpautoload",
                'link' => "https://gray-code.com/php/",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'member_id' => 1,
                'team_id' => 1,
                'language_id' => 3,
                'code' => null,
                'command' => null,
                'link' => "http://js.studio-kingdom.com/javascript/",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'member_id' => 1,
                'team_id' => 1,
                'language_id' => 4,
                'code' => null,
                'command' => "php artisan serve",
                'link' => null,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'member_id' => 1,
                'team_id' => 2,
                'language_id' => 4,
                'code' => null,
                'command' => "composer require barryvdh/laravel-debugbar",
                'link' => "https://readouble.com/",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'member_id' => 1,
                'team_id' => 2,
                'language_id' => 4,
                'code' => null,
                'command' => "php artisan migrate",
                'link' => null,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'member_id' => 1,
                'team_id' => 2,
                'language_id' => 1,
                'code' => null,
                'command' => null,
                'link' => "http://www.htmq.com/",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'member_id' => 1,
                'team_id' => 2,
                'language_id' => 2,
                'code' => null,
                'command' => null,
                'link' => "https://qiita.com/soarflat/items/4a302e0cafa21477707f",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
        ]);
    }
}
